name: Docker Image CI

on: push


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: show cpuinfo
      run: |
        cat /proc/cpuinfo
        free -h
        df -h
    - name: docker version
      run: docker version

    - name: Build the Docker image

      run: |
        docker ps
        docker login --username=${{secrets.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}} registry.cn-shenzhen.aliyuncs.com
        docker build . --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/devan/flask-demo:v1
        docker push registry.cn-shenzhen.aliyuncs.com/devan/flask-demo:v1
        
