name: Docker Image CI

on: push


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker version
      run: docker version

    - name: Build the Docker image

      run: |
        docker ps
        docker login --username=tb33599345 --password=abcd1234 registry.cn-shenzhen.aliyuncs.com
        docker build . --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/devan/flask-demo:$(date)
        docker push registry.cn-shenzhen.aliyuncs.com/devan/flask-demo:$(date)
        
